# Generated by Django 4.2.4 on 2023-08-24 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_For_Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('happy_or_not', models.BooleanField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('defucalt', models.BooleanField()),
                ('notes_for_me', models.TextField(max_length=5000)),
                ('who_with_me', models.CharField(choices=[('Alone', 'Alone'), ('Abdelmonem', 'Abdelmonem'), ('Moahmed', 'Mohamed')], max_length=20)),
                ('were_this_land', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_saler', models.CharField(max_length=100)),
                ('name_buyer', models.CharField(max_length=100)),
                ('hight', models.FloatField()),
                ('width', models.FloatField()),
                ('hypotenuse', models.FloatField()),
                ('price', models.FloatField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('subtitle_information_for_land', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='image_land')),
            ],
        ),
    ]
